parse-dashboard:
  #build: .
  image: yongjhih/parse-dashboard
  environment:
    PARSE_SERVER_URL: $PARSE_SERVER_URL
    PARSE_APP_ID: $PARSE_APP_ID
    PARSE_MASTER_KEY: $PARSE_MASTER_KEY
    PARSE_JS_KEY: $PARSE_JS_KEY
    PARSE_REST_KEY: $PARSE_REST_KEY
    PARSE_APP_NAME: $PARSE_APP_NAME
    SERVER_URL: $SERVER_URL
    APP_ID: $APP_ID
    MASTER_KEY: $MASTER_KEY
    APP_NAME: $APP_NAME
    PARSE_DASHBOARD_ALLOW_INSECURE_HTTP: $PARSE_DASHBOARD_ALLOW_INSECURE_HTTP
    USER1: $USER1
    USER1_PASSWORD: $USER1_PASSWORD
  ports:
    - "4040:4040"

# vim:set et ts=2 sw=2:
